# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodgroup',
            fields=[
                ('bloodgroupId', models.AutoField(primary_key=True, serialize=False)),
                ('bloodgroup', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bloodgroupId', models.ForeignKey(db_column='bloodgroupid', on_delete=django.db.models.deletion.DO_NOTHING, to='patient.Bloodgroup')),
            ],
        ),
    ]
