# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodgroup',
            old_name='bloodgroup',
            new_name='bloodgroupDetails',
        ),
    ]
