# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20170815_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodgroup',
            name='bloodgroupType',
            field=models.CharField(default='Z', max_length=10),
        ),
    ]
