# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_bloodgroup_bloodgrouptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='bloodgroupType',
            field=models.CharField(default='+', max_length=10),
        ),
    ]
